# Generated by Django 4.0.8 on 2023-07-24 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swingtime', '0003_alter_event_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='related_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='related_id'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(max_length=1000, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=100, verbose_name='title'),
        ),
    ]
